INSERT INTO config_category VALUES (1, 'General', 0, true);
INSERT INTO config_category VALUES (2, 'L2A Atmospheric Correction', 1, true);
INSERT INTO config_category VALUES (3, 'L3A Composite', 2, true);
INSERT INTO config_category VALUES (4, 'L3B Vegetation Status', 3, true);
INSERT INTO config_category VALUES (5, 'L4A Crop Mask', 5, true);
INSERT INTO config_category VALUES (6, 'L4B Crop Type', 6, true);
INSERT INTO config_category VALUES (7, 'Archiver', 7, true);
INSERT INTO config_category VALUES (8, 'Executor', 8, false);
INSERT INTO config_category VALUES (12, 'Dashboard', 9, false);
INSERT INTO config_category VALUES (13, 'Monitoring Agent', 10, false);
INSERT INTO config_category VALUES (14, 'Resources', 11, false);
INSERT INTO config_category VALUES (15, 'Downloader', 12, true);
INSERT INTO config_category VALUES (17, 'Site', 14, false);
INSERT INTO config_category VALUES (18, 'L3E Pheno NDVI', 4, true);
INSERT INTO config_category VALUES (24, 'S2A L3C LAI N-Days Reprocessing', 4, true);
INSERT INTO config_category VALUES (25, 'S2A L3D LAI Fitted Reprocessing', 4, true);
