#ifndef GLOBALDEFS_H
#define GLOBALDEFS_H

#define NDVI_QUANTIFICATION_VALUE   10000
#define NO_DATA_VALUE               -10000

#define WEIGHT_NO_DATA_VALUE        -10000

#define NO_DATA_EPSILON 0.0001f

typedef enum {IMG_FLG_NO_DATA=0, IMG_FLG_CLOUD=1, IMG_FLG_SNOW=2, IMG_FLG_WATER=3, IMG_FLG_LAND=4, IMG_FLG_CLOUD_SHADOW=5, IMG_FLG_SATURATION=6} FlagType;


#endif //GLOBALDEFS_H
