/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ProcessorsExecutorAdapter -p ProcessorsExecutorProxy org.esa.sen2agri.processorsExecutor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PROCESSORSEXECUTORADAPTER_H_1433344913
#define PROCESSORSEXECUTORADAPTER_H_1433344913

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.esa.sen2agri.processorsExecutor
 */
class ProcessorsExecutorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.esa.sen2agri.processorsExecutor")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.esa.sen2agri.processorsExecutor\">\n"
"    <method name=\"ExecuteProcessor\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"jsonCfgStr\"/>\n"
"    </method>\n"
"    <method name=\"StopProcessorJob\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"jobName\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ProcessorsExecutorAdaptor(QObject *parent);
    virtual ~ProcessorsExecutorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool ExecuteProcessor(const QString &jsonCfgStr);
    bool StopProcessorJob(const QString &jobName);
Q_SIGNALS: // SIGNALS
};

#endif
