/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ProcessorsExecutorAdapter -p ProcessorsExecutorProxy org.esa.sen2agri.processorsExecutor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ProcessorsExecutorAdapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ProcessorsExecutorAdaptor
 */

ProcessorsExecutorAdaptor::ProcessorsExecutorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ProcessorsExecutorAdaptor::~ProcessorsExecutorAdaptor()
{
    // destructor
}

bool ProcessorsExecutorAdaptor::ExecuteProcessor(const QString &jsonCfgStr)
{
    // handle method call org.esa.sen2agri.processorsExecutor.ExecuteProcessor
    bool out0;
    QMetaObject::invokeMethod(parent(), "ExecuteProcessor", Q_RETURN_ARG(bool, out0), Q_ARG(QString, jsonCfgStr));
    return out0;
}

bool ProcessorsExecutorAdaptor::StopProcessorJob(const QString &jobName)
{
    // handle method call org.esa.sen2agri.processorsExecutor.StopProcessorJob
    bool out0;
    QMetaObject::invokeMethod(parent(), "StopProcessorJob", Q_RETURN_ARG(bool, out0), Q_ARG(QString, jobName));
    return out0;
}

