#!/bin/bash
function try {
    "$@"
    code=$?
    if [ $code -ne 0 ]
    then
        echo "$1 did not work: exit status $code"
        exit 1
    fi
}
if [[ $# -ne 2 ]]; then
    echo "The xml file with full path for the SPOT product should be given. The output directory should be given" 1>&2
    exit 1
fi
try otbcli SpotMaskHandler ../../sen2agri-processors-build/Composite/SpotMaskHandler/ -xml $1 -out $2/cws.tif
try otbcli ResampleAtS2Res ../../sen2agri-processors-build/Composite/ResampleAtS2Res/ -xml $1 -spotmask $2/cws.tif -outres10 $2/res10.tif -outres20 $2/res20.tif -outcmres10 $2/cloud_res10.tif -outwmres10 $2/water_res10.tif -outsmres10 $2/snow_res10.tif -outaotres10 $2/aot_res10.tif -outcmres20 $2/cloud_res20.tif -outwmres20 $2/water_res20.tif -outsmres20 $2/snow_res20.tif -outaotres20 $2/aot_res20.tif 
