create table product_details_l4c(
    product_id int not null references product(id),
    "NewID" int not null,
    orig_id text not null,
    country text not null,
    year int not null,
    main_crop text not null,
    veg_start text not null,
    h_start text not null,
    h_end text not null,
    practice text not null,
    p_type text not null,
    p_start text not null,
    p_end text not null,
    l_week text not null,
    m1 text not null,
    m2 text not null,
    m3 text not null,
    m4 text not null,
    m5 text not null,
    h_week text not null,
    h_w_start text not null,
    h_w_end text not null,
    h_w_s1 text not null,
    m6 text not null,
    m7 text not null,
    m8 text not null,
    m9 text not null,
    m10 text not null,
    c_index text not null,
    s1_pix text not null,
    s1_gaps text not null,
    h_s1_gaps text not null,
    p_s1_gaps text not null,
    constraint product_details_l4c_pkey primary key(product_id, "NewID")
);
