#!/bin/sh
git clone https://github.com/GrayShade/OTB.git
mkdir OTB-BUILD
cd OTB-BUILD
cmake ../OTB/SuperBuild \
	-DCMAKE_INSTALL_PREFIX=~/otb-install/usr \
	-DCMAKE_BUILD_TYPE=RelWithDebInfo \
	-DBUILD_TESTING=OFF \
	-DGDAL_CONFIG=/usr/bin/gdal-config \
	-DGDAL_INCLUDE_DIR=/usr/include/gdal \
	-DGDAL_LIBRARY=/usr/lib64/libgdal.so \
	-DOTB_USE_MUPARSERX=OFF \
	-DOTB_WRAP_PYTHON=ON \
	-DUSE_SYSTEM_BOOST=ON \
	-DUSE_SYSTEM_CURL=ON \
	-DUSE_SYSTEM_EXPAT=ON \
	-DUSE_SYSTEM_FFTW=ON \
	-DUSE_SYSTEM_GDAL=ON \
	-DUSE_SYSTEM_GEOS=ON \
	-DUSE_SYSTEM_GEOTIFF=ON \
	-DUSE_SYSTEM_ITK=OFF \
	-DUSE_SYSTEM_JPEG=ON \
	-DUSE_SYSTEM_LIBKML=OFF \
	-DUSE_SYSTEM_LIBSVM=ON \
	-DUSE_SYSTEM_MUPARSER=ON \
	-DUSE_SYSTEM_MUPARSERX=ON \
	-DUSE_SYSTEM_OPENCV=ON \
	-DUSE_SYSTEM_OPENJPEG=ON \
	-DUSE_SYSTEM_OPENTHREADS=OFF \
	-DUSE_SYSTEM_OSSIM=OFF \
	-DUSE_SYSTEM_PCRE=ON \
	-DUSE_SYSTEM_PNG=ON \
	-DUSE_SYSTEM_PROJ=ON \
	-DUSE_SYSTEM_QT4=ON \
	-DUSE_SYSTEM_SQLITE=ON \
	-DUSE_SYSTEM_SWIG=ON \
	-DUSE_SYSTEM_TIFF=ON \
	-DUSE_SYSTEM_TINYXML=ON \
	-DUSE_SYSTEM_ZLIB=ON
mkdir ~/tmp
fpm -s dir -t rpm -n otb -v 5.0 -C ~/otb-install/ -p --workdir ~/tmp otb-VERSION.fc22.ARCH.rpm usr
