CREATE OR REPLACE FUNCTION sp_get_parameters(
IN _prefix CHARACTER VARYING DEFAULT NULL) RETURNS 
TABLE (key CHARACTER VARYING, value CHARACTER VARYING) AS $$
BEGIN

RETURN QUERY SELECT config.key, config.value FROM config WHERE CASE WHEN _prefix IS NOT NULL THEN config.key like 'prefix%' ELSE 1 = 1 END;

END;
$$ LANGUAGE plpgsql;